site_name: The Annotated Tnn
theme:
    name: material
    # name: bootstrap4
markdown_extensions:
    - mdx_math
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML